import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowLeft, Wifi, Check, Phone, Camera, Tv } from 'lucide-react';
import { profileData } from '../data/profile';
import './wifi-landing.css';

const plans = [
  { name: 'Internet', price: 195000, label: 'KẾT NỐI MỖI NGÀY', items: ['Internet cho học tập và làm việc', 'Tư vấn Wi-Fi theo không gian nhà', 'Kiểm tra hạ tầng trước đăng ký'] },
  { name: 'Combo V.VIP', price: 220000, label: 'KẾT NỐI + GIẢI TRÍ', items: ['Internet + FPT Play', 'Giải trí trên ứng dụng FPT Play', 'Thiết bị Box tính riêng nếu cần'] },
  { name: 'Triple V.VIP', price: 230000, label: 'THÊM CAMERA CHO TỔ ẤM', items: ['Internet + FPT Play + lưu trữ camera', 'Tặng camera đầu tiên theo điều kiện gói', 'Xác nhận mẫu camera và thời gian lưu trữ'] },
];
const money = (value: number) => new Intl.NumberFormat('vi-VN').format(value);
export default function WifiLanding() {
  const root = useRef<HTMLDivElement>(null);
  const [annual, setAnnual] = useState(false);
  const contact = profileData.contact;
  useEffect(() => {
    const previous = document.title;
    document.title = 'Internet FPT & Combo V.VIP | Hải · 0764 640 415';
    if (!window.matchMedia('(prefers-reduced-motion: reduce)').matches && 'IntersectionObserver' in window) {
      const nodes = root.current?.querySelectorAll('.wl-reveal');
      const observer = new IntersectionObserver(entries => entries.forEach(entry => { if(entry.isIntersecting) { entry.target.classList.add('wl-visible'); observer.unobserve(entry.target); } }), {threshold: .08});
      nodes?.forEach(node => { node.classList.add('wl-ready'); observer.observe(node); });
      return () => { observer.disconnect(); document.title = previous; };
    }
    return () => { document.title = previous; };
  }, []);
  return <div className="wl" ref={root}>
    <header className="wl-nav"><a href="/" className="wl-brand">HẢI<span> / FPT</span></a><nav><a href="#pricing">Gói cước</a><a href="#benefits">Combo</a><a href="#questions">Hỏi đáp</a></nav><a href={contact.zaloUrl} target="_blank" rel="noopener noreferrer" className="wl-nav-cta">Nhắn Hải <ArrowUpRight size={16}/></a></header>
    <main>
      <section className="wl-hero wl-wrap"><div className="wl-hero-copy"><a className="wl-back" href="/#products"><ArrowLeft size={14}/> Về portfolio</a><p className="wl-kicker">INTERNET FPT · TƯ VẤN CÙNG HẢI</p><h1>Kết nối cả nhà.<br/><em>Mở thêm trải nghiệm.</em></h1><p>Wi-Fi cho ngày làm việc. FPT Play cho tối thư giãn. Camera để gần nhà hơn, dù bạn ở đâu.</p><div className="wl-cta-row"><a href="#pricing" className="wl-btn">Khám phá gói cước <ArrowUpRight size={18}/></a><a className="wl-text-link" href={`tel:${contact.phone}`}><Phone size={16}/>{contact.phoneFormatted}</a></div><div className="wl-hero-stats"><span><b>195k</b>Internet / tháng</span><span><b>3 trong 1</b>Kết nối · Giải trí · Camera</span></div></div><div className="wl-visual" onPointerMove={e => { if(e.pointerType !== 'mouse' || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; const r=e.currentTarget.getBoundingClientRect(); e.currentTarget.style.setProperty('--rx', `${-(e.clientY-r.top-r.height/2)/r.height*7}deg`); e.currentTarget.style.setProperty('--ry', `${(e.clientX-r.left-r.width/2)/r.width*9}deg`); }} onPointerLeave={e => { e.currentTarget.style.setProperty('--rx','0deg'); e.currentTarget.style.setProperty('--ry','0deg'); }}><div className="wl-orbit"/><img src="/images/fpt-home-devices.jpg" alt="Thiết bị Wi-Fi, FPT Play và camera FPT"/><span className="wl-float wl-float-top"><Wifi size={21}/> Một nhà. Đủ kết nối.</span><span className="wl-float wl-float-bottom"><Camera size={20}/><span>Triple V.VIP<b>230k / tháng</b></span></span></div></section>
      <section id="pricing" className="wl-pricing wl-reveal"><div className="wl-wrap"><div className="wl-heading"><div><p className="wl-kicker">CHỌN THEO NHU CẦU</p><h2>Rõ gói cước.<br/>Dễ chọn cho nhà mình.</h2></div><div className="wl-switch" role="group" aria-label="Kỳ thanh toán"><button aria-pressed={!annual} onClick={() => setAnnual(false)}>Hàng tháng</button><button aria-pressed={annual} onClick={() => setAnnual(true)}>Đóng 12 tháng</button></div></div><div className="wl-plans">{plans.map((p,i) => <article className={`wl-plan ${i===2?'wl-featured':''}`} key={p.name}>{i===2 && <span className="wl-recommend">COMBO CAMERA NỔI BẬT</span>}<p className="wl-plan-label">{p.label}</p><h3>{p.name}</h3><div className="wl-price">{money(annual?p.price*12:p.price)}<span>đ / {annual?'12 tháng':'tháng'}</span></div><p className="wl-price-note">{annual?'Tổng cước trước hỗ trợ riêng khi đóng 12 tháng.':'Cước hàng tháng, chưa cộng phí lắp đặt.'}</p><ul>{p.items.map(t => <li key={t}><Check size={16}/>{t}</li>)}</ul><a className="wl-btn" href={contact.zaloUrl} target="_blank" rel="noopener noreferrer">Hỏi Hải về gói này <ArrowUpRight size={17}/></a></article>)}</div><div className="wl-install"><div><b>Lắp đặt: 300.000đ</b><p>Có thể hỗ trợ 100.000–300.000đ. Mức áp dụng được Hải xác nhận theo từng trường hợp.</p></div><div><b>Đóng trước 12 tháng?</b><p>Có hỗ trợ thêm. Nhắn Hải để biết mức hỗ trợ và tổng thanh toán trước khi đăng ký.</p></div></div><p className="wl-terms">Mức cước theo thông tin tư vấn của Hải. Gói áp dụng, quà tặng, thiết bị, VAT và phí phát sinh sẽ được xác nhận theo địa chỉ và chính sách tại thời điểm đăng ký. Camera tặng thuộc gói Triple phù hợp; không mặc định tặng ở mọi gói Combo.</p></div></section>
      <section id="benefits" className="wl-wrap wl-benefits wl-reveal"><div className="wl-poster"><img src="/images/fpt-combo-poster.jpg" alt="Giới thiệu combo FPT Internet, FPT Play và Camera" loading="lazy"/><a href="/images/fpt-combo-poster.jpg" target="_blank" rel="noopener noreferrer">Xem poster đầy đủ <ArrowUpRight size={16}/></a></div><div><p className="wl-kicker">MỘT HỆ SINH THÁI CHO TỔ ẤM</p><h2>Không chỉ là Wi-Fi.</h2>{[{Icon:Wifi,title:'Kết nối để làm điều bạn muốn',text:'Học online, làm việc và sử dụng nhiều thiết bị. Hải tư vấn theo diện tích và nhu cầu thực tế.'},{Icon:Tv,title:'Thêm thời gian giải trí cùng nhau',text:'Combo có FPT Play. Nội dung và quyền xem theo gói đăng ký; Box được tư vấn riêng nếu bạn cần.'},{Icon:Camera,title:'Thêm một góc nhìn về ngôi nhà',text:'Triple có camera và dịch vụ lưu trữ theo gói. Mẫu trong nhà / ngoài trời và thời gian lưu trữ sẽ được xác nhận trước lắp đặt.'}].map(({Icon,title,text}) => <div className="wl-benefit" key={title}><Icon/><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></section>
      <section className="wl-process wl-wrap wl-reveal"><p className="wl-kicker">BẮT ĐẦU THẬT ĐƠN GIẢN</p><h2>Ba bước, Hải đồng hành.</h2><div>{[{title:'Gửi địa chỉ',text:'Nhắn Zalo vị trí lắp đặt và nhu cầu sử dụng.'},{title:'Chọn gói phù hợp',text:'Kiểm tra hạ tầng, chốt cước và hỗ trợ áp dụng.'},{title:'Hẹn lịch lắp đặt',text:'Thống nhất thủ tục và thời gian phù hợp với bạn.'}].map((p,i) => <article key={p.title}><span>0{i+1}</span><h3>{p.title}</h3><p>{p.text}</p></article>)}</div></section>
      <section id="questions" className="wl-faq wl-wrap wl-reveal"><div><p className="wl-kicker">BẠN CÓ THỂ ĐANG THẮC MẮC</p><h2>Hỏi trước.<br/>An tâm chọn sau.</h2></div><div>{[{q:'195k, 220k và 230k khác nhau thế nào?',a:'195k là Internet; 220k là combo Internet và FPT Play; 230k là Triple thêm camera và dịch vụ lưu trữ theo gói áp dụng.'},{q:'Có chắc được miễn phí lắp đặt không?',a:'Phí lắp đặt là 300.000đ. Hải có thể hỗ trợ từ 100.000đ đến 300.000đ tùy trường hợp; chỉ xác nhận mức cuối cùng sau khi kiểm tra.'},{q:'Camera được tặng là mẫu nào?',a:'Camera đầu tiên được tặng theo điều kiện gói Triple áp dụng. Nhắn Hải để xác nhận mẫu, nhu cầu trong nhà hoặc ngoài trời và thời gian lưu trữ. Không mặc định là mẫu trong ảnh minh họa.'},{q:'Đóng 12 tháng được giảm bao nhiêu?',a:'Có hỗ trợ thêm nhưng chưa có mức cố định. Số tiền hiển thị là cước tháng nhân 12, chưa trừ hỗ trợ và chưa cộng phí lắp đặt hoặc thiết bị.'}].map(f => <details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</div></section>
      <section className="wl-final"><div className="wl-wrap"><p className="wl-kicker">HẢI · FPT TELECOM CẦN THƠ</p><h2>Nhà cần kết nối.<br/>Hải sẵn sàng lắng nghe.</h2><a href={contact.zaloUrl} className="wl-btn" target="_blank" rel="noopener noreferrer">Tư vấn qua Zalo <ArrowUpRight size={19}/></a><a className="wl-call" href={`tel:${contact.phone}`}>{contact.phoneFormatted}</a></div></section>
    </main><footer className="wl-footer"><span>Trang tư vấn cá nhân của Nguyễn Chí Hải</span><a href="/">Về portfolio <ArrowUpRight size={14}/></a></footer>
  </div>;
}
